### ISSUE TITLE
Add Metaverse to Roadmap

### ISSUE THREAD

**Issue by mike7seven** [circa10a/blockerized-dockchain#1]
If we are are not planning for the metaverse with this project, then I don't even know what we are doing anymore.

**Comment by circa10a** [comment]
Addressed above 👍 . Please close if this solves your issue

**Comment by mike7seven** [comment]
This is great. I think we are close. As a Project Manager I gave some realistic timelines to the customer and leadership that we would have this feature completed by years end. I even added in a week of padding just in case. If you all have to work through the holidays, no worries. Thanks!

**Comment by circa10a** [comment]
![alt text](https://media.giphy.com/media/o7lhOIWax9hQs/giphy.gif)

**Comment by mike7seven** [comment]
Just checking in to see if we have made any progress on the Metaverse implementation?

**Comment by circa10a** [comment]
@mike7seven Actually yes! There has been progress!

![alt text](https://i.imgur.com/yEVxFaj.jpeg)
