### ISSUE TITLE
Stale?

### ISSUE THREAD

**Issue by j0sh3rs** [circa10a/blockerized-dockchain#3]
This project seems to be stalled out. Is there any hope it will get revived and we can see some progress on the roadmap items? My not-yet-funded-or-planned-for startup heavily depends on containerized blockchains on the metaverse platform

**Comment by j0sh3rs** [comment]
Please also add GCP support. It's the superior cloud and AWS is on its way out.

**Comment by circa10a** [comment]
Not stale, just perfect and stable implementation.

> GCP Support

https://www.apa.org/topics/crisis-hotlines

You can thank me later.

**Comment by circa10a** [comment]
The project is perfect and doesn't need any further enhancements now or in the indefinite future.
